# TP 01

**Alumno**: Matias Tripode

## Parte I

In [8]:
%matplotlib qt

import numpy as np
import cv2 as cv
import matplotlib.pyplot as plt

**1) Implementar el algoritmo White Patch para librarnos de las diferencias de color de iluminación.**

In [9]:
def white_patch(input_image_rgb: np.ndarray) -> np.ndarray:
    im_r, im_g, im_b = cv.split(input_image_rgb)
    # red
    im_r_max = im_r.max()
    if im_r_max == 255:
        im_r_max = np.percentile(im_r, 95)
    # green
    im_g_max = im_g.max()
    if im_g_max == 255:
        im_g_max = np.percentile(im_g, 95)
    # blue
    im_b_max = im_b.max()
    if im_b_max == 255:
        im_b_max = np.percentile(im_b, 95)

    new_r = np.uint8((255/im_r_max)*im_r)
    new_g = np.uint8((255/im_g_max)*im_g)
    new_b = np.uint8((255/im_b_max)*im_b)

    return cv.merge((new_r,new_g,new_b))

**2) Mostrar los resultados obtenidos y analizar las posibles fallas (si es que las hay) en el caso de
White patch.**

In [10]:
# Descomentar alguna de las lineas para ver el procesado de la imagen con White-patch
img_color = cv.imread('white_patch/test_blue.png')
#img_color = cv.imread('white_patch/test_green.png')
#img_color = cv.imread('white_patch/test_red.png')
#img_color = cv.imread('white_patch/wp_blue.jpg')
#img_color = cv.imread('white_patch/wp_green.png')
#img_color = cv.imread('white_patch/wp_red.png')

# Para las siguientes dos imagenes, White-patch produce la misma imagen. Ver explicacion abajo.
#img_color = cv.imread('white_patch/wp_green2.jpg')
#img_color = cv.imread('white_patch/wp_red2.jpg')

imgRGB = cv.cvtColor(img_color, cv.COLOR_BGR2RGB)

imgRGB_filtrada = white_patch(imgRGB)

# Nueva figura
fig = plt.figure()

# Imagen original
ax1=plt.subplot(221)
ax1.imshow(imgRGB, cmap='gray', vmin=0, vmax=255)
ax1.set_title('Original')

# Imagen modificada con white-patch
ax2=plt.subplot(222)
ax2.imshow(imgRGB_filtrada, cmap='gray', vmin=0, vmax=255)
ax2.set_title('White-patch')

plt.show()



**Analizar las posibles fallas**

Para imagenes como `wp_green2.jpg` y `wp_red2.jpg` que tienen dos canales con valores `0` o muy cercanos al `0`, el algoritmo de `White-Patch` produce la misma imagen.

Por ejemplo vemos un extracto de  `wp_green2.jpg`  que practicamente tiene valores en el canal `G`:
```
...
[[  3  97   3]
  [  3  97   3]
  [  0  92   0]
  ...
  [  0 252   0]
  [  0 251   0]
  [  0 251   0]]
...
```


## Parte II

**1. Para las imágenes img1_tp.png y img2_tp.png leerlas con OpenCV en escala de grisas y
visualizarlas**

In [11]:
%matplotlib qt

import numpy as np
import cv2 as cv
import matplotlib.pyplot as plt

In [12]:
# Cargar una imagen en modo monocromático (un canal)
img1_tp = cv.imread('img1_tp.png', cv.IMREAD_GRAYSCALE)
img2_tp = cv.imread('img2_tp.png', cv.IMREAD_GRAYSCALE)

# Nueva figura
fig = plt.figure()

# Imagen img1_tp
ax1=plt.subplot(221)
ax1.imshow(img1_tp, cmap='gray', vmin=0, vmax=255)
ax1.set_title('img1_tp')

# Imagen img2_tp
ax2=plt.subplot(222)
ax2.imshow(img2_tp, cmap='gray', vmin=0, vmax=255)
ax2.set_title('img2_tp')

plt.show()


**2) Elija el numero de bins que crea conveniente y grafique su histograma**

In [13]:
# Nueva figura
fig = plt.figure()

# Imagen img1_tp
ax1=plt.subplot(221)
ax1.imshow(img1_tp, cmap='gray', vmin=0, vmax=255)
ax1.set_title('img1_tp')

ax3=plt.subplot(223)
ax3.hist(img1_tp, bins=32, edgecolor='black')
ax3.set_title('Histograma img1_tp')

# Imagen img2_tp
ax2=plt.subplot(222)
ax2.imshow(img2_tp, cmap='gray', vmin=0, vmax=255)
ax2.set_title('img2_tp')

ax4=plt.subplot(224)
ax4.hist(img2_tp, bins=32, edgecolor='black')
ax4.set_title('Histograma img2_tp')
plt.show()

**Comparando histogramas, explicar lo que se observa**

- Vemos que la distribución de intensidades de la imagen `img1_tp.png` es suave y continua. Esto indicaria que la imagen no fue modificada digitalmente.
- En cambio vemos en el histograma de `img2_tp.png` quizas se le aplico una alteración de
contraste.

**Si tuviera que entrenar un modelo de clasificación/detección de imágenes, considera que puede ser de utilidad tomar como ‘features’ a los histogramas?**
- Si tuviera que clasificar imagenes entre modificadas digitalemente y cuales no, entonces si podriamos utilizar `histogramas` como `features` (por lo visto en el punto anterior)